# Generated by Django 5.2 on 2025-04-29 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Upload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload_type', models.CharField(choices=[('image', 'Image'), ('audio', 'Audio'), ('video', 'Video')], max_length=10)),
                ('original_file', models.FileField(upload_to='original_files/')),
                ('stego_file', models.FileField(blank=True, null=True, upload_to='stego_files/')),
                ('upload_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
